# Don't print a new line at the start of the prompt
add_newline = false

prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "php",
    "nix_shell",
    "memory_usage",
    "env_var",
    "cmd_duration",
    "custom",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

